### ISSUE TITLE
Todo list (deprecated)

### ISSUE THREAD

**Issue by qexat** [Geoxor/Shaii#81]
### Roles & Leveling

- [x] Add auto role Ghosts to newcomers
- [ ] Add a leveling system
- [ ] Add auto roles on certain levels

### Commands

- [x] Add `~mute` command (uses Timeout Discord feature)

### Embed help command response

- [ ] Implement interactions
- [ ] Add working button pagination with multiple pages

### Testing

- [ ] Rewrite unit test script

**Comment by qexat** [comment]
I just copied the issue from my own repo, it probably needs some changes
